# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US"
title: Henk van der Schuur
email: hwschuur@gmail.com
description: Henk van der Schuur — # this means to ignore newlines until "baseurl:"
seo_description: dr. Henk van der Schuur
seo_title: dr. Henk van der Schuur
minimal_mistakes_skin: dirt # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: false
atom_feed:
  hide                   : true # true, false (default)

analytics:
  provider: google-gtag
  google:
    tracking_id: G-M8FJLTPT2Q
    anonymize_ip: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.0
# Outputting
permalink: /:categories/:year/:month/:day/:title/
paginate: 7 # amount of posts to show
paginate_path: /page:num/
timezone: nl # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - _posts/archive/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  avatar : "/assets/images/bio-photo.png"
  bio    : "Customer Director at Schuberg Philis. Software Production Enthusiast. Pragmatic Perfectionist."
  twitter: "hwschuur"
  linkedin: "hwschuur"
  email: hwschuur@gmail.com
  descriptions: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      show_date: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      related: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/